[phases.setup]
nixPkgs = ["nodejs", "bash"]

[phases.install] 
cmds = ["npm ci"]

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh"]

[start]
cmd = "NODE_ENV=production node dist/index.js"

[variables]
NODE_ENV = "production"