[phases.setup]
nixPkgs = ["nodejs", "bash"]

[phases.install] 
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm ci",
  "npx vite build --config vite.config.production.ts",
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist",
  "mkdir -p uploads"
]

[start]
cmd = "NODE_ENV=production node dist/index.js"

[variables]
NODE_ENV = "production"